# version: '3.8'

# services:
#   dind:
#     image: docker:dind
#     privileged: true
#     container_name: docker_in_docker
#     restart: always
#     networks:
#       - app_network
#     environment:
#       - DOCKER_TLS_CERTDIR=

#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: backend_container
#     depends_on:
#       - dind
#     ports:
#       - "5000:5000"
#     environment:
#       - DOCKER_HOST=tcp://dind:2375
#     networks:
#       - app_network

#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: frontend_container
#     depends_on:
#       - backend
#     working_dir: /app/frontend
#     command: >
#       sh -c "npm install && npm run build && npx serve -s dist -l 3000"
#     ports:
#       - "3000:3000"
#     networks:
#       - app_network

# networks:
#   app_network:



version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: combined_app_container
    ports:
      - "5000:5000"
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_network

networks:
  app_network:

